### ISSUE TITLE
README documentation links broken

### ISSUE THREAD

**Issue by dtch1997** [balrog-ai/BALROG#3]
The links to "Evaluation Guide" and "Agent Development" in the README do not work currently

**Comment by DavidePaglieri** [comment]
Hello, these links seem to work fine for me. Closing this, reopen if you still have problems.

**Comment by DavidePaglieri** [comment]
Actually, we see what's the problem here. The links point to a private version of BALROG-dev that we use for development. Fixed in #5. Thank you for spotting!
